FROM centos:centos7

RUN  yum install epel-release -y \
    && yum install bc jq pwgen python-pip python-devel gcc git libselinux-python wget vim -y \
    && yum install https://centos7.iuscommunity.org/ius-release.rpm -y \
    && yum install python36u -y \
    && yum install openssl  -y \
    && yum install sshpass -y \
    && ln -s /usr/bin/python3.6 /usr/bin/python3

RUN pip install --upgrade pip

RUN pip install \
    ansible==2.6.0 \
    asn1crypto==0.24.0 \
    bcrypt==3.1.6 \
    cffi==1.11.5 \
    cryptography==2.5 \
    enum34==1.1.6 \
    ipaddress \
    git+git://github.com/apache/libcloud.git@v2.3.0 \
    google-api-python-client==1.6.5 \
    google-auth==1.4.1 \
    google-auth-httplib2==0.0.3 \
    httplib2==0.10.3 \
    ansible-modules-hashivault==3.9.4 \
    ansible-vault==1.1.1 \
    netaddr==0.7.19 \
    Jinja2==2.10 \
    MarkupSafe==1.1.0 \
    netaddr==0.7.19 \
    paramiko==2.4.2 \
    pyasn1==0.4.5 \
    pycparser==2.19 \
    PyNaCl==1.3.0 \
    PyYAML==3.13 \
    six==1.12.0

COPY files/kubernetes.repo /etc/yum.repos.d/kubernetes.repo
RUN  yum install -y kubectl-1.12.1

WORKDIR /tmp
RUN  wget -q https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-linux-amd64.tar.gz -O /tmp/helm-2.11.0.tar.gz \
    && tar xzf  /tmp/helm-2.11.0.tar.gz \
    && mv linux-amd64/helm /usr/local/bin/helm \
    && rm -rf /tmp/helm-2.11.0.tar.gz /tmp/linux-amd64

WORKDIR /
ADD files/init.sh .
ENTRYPOINT ["/init.sh"]