FROM centos:centos7

RUN  yum install epel-release -y \
    && yum install bc jq pwgen python-pip python-devel gcc git libselinux-python wget vim bash-completion -y \
    && yum install https://centos7.iuscommunity.org/ius-release.rpm -y \
    && yum install python36u -y \
    && yum install openssl  -y \
    && yum install sshpass -y \
    && yum install autoconf automake libtool python-devel -y \
    && yum install telnet nc -y

RUN pip install --upgrade pip

RUN pip install \
    ansible==2.7.11 \
    netaddr==0.7.19 \
    pycrypto==2.6.1 \
    httpie==0.9.9 \
    git+git://github.com/apache/libcloud.git@v2.3.0 \
    google-api-python-client==1.6.5 \
    google-auth==1.4.1 \
    google-auth-httplib2==0.0.3 \
    ipaddress \
    httplib2==0.10.3 \
    ansible-modules-hashivault==3.9.4 \
    ansible-vault==1.1.1 \
    apache-libcloud==2.3.0 \
    asn1crypto==0.24.0 \
    backports.ssl-match-hostname==3.5.0.1 \
    bcrypt==3.1.4 \
    cachetools==2.1.0 \
    certifi==2018.8.13 \
    cffi==1.11.5 \
    chardet==3.0.4 \
    cryptography==2.3 \
    docker \
    enum34==1.1.6 \
    hvac==0.6.3 \
    idna==2.7 \
    Jinja2==2.10 \
    MarkupSafe==1.0 \
    netaddr==0.7.19 \
    oauth2client==4.1.2 \
    paramiko==2.4.1 \
    pyasn1==0.4.4 \
    pyasn1-modules==0.2.2 \
    pycparser==2.18 \
    Pygments==2.2.0 \
    pyjq==2.3.1 \
    PyNaCl==1.2.1 \
    PyYAML==3.13 \
    requests==2.19.1 \
    rsa==3.4.2 \
    six==1.11.0 \
    uritemplate==3.0.0 \
    urllib3==1.23 \
    ovh==0.5.0 \
    proxmoxer==1.0.3 \
    websocket-client==0.54.0 \
    mitogen==0.2.9

RUN  yum remove -y autoconf automake libtool python-devel

COPY files/kubernetes.repo /etc/yum.repos.d/kubernetes.repo
RUN  yum install -y kubectl-1.12.1
RUN  kubectl completion bash > /etc/bash_completion.d/kubectl

COPY files/mongorepo.repo /etc/yum.repos.d/mongorepo.repo
RUN  yum install -y mongodb-org-tools-3.6.14 mongodb-org-shell-3.6.14

WORKDIR /tmp
RUN  wget -q https://storage.googleapis.com/kubernetes-helm/helm-v2.14.2-linux-amd64.tar.gz -O /tmp/helm-2.14.2.tar.gz \
    && tar xzf  /tmp/helm-2.14.2.tar.gz \
    && mv linux-amd64/helm /usr/local/bin/helm \
    && rm -rf /tmp/helm-2.14.2.tar.gz /tmp/linux-amd64

WORKDIR /
ADD files/init.sh .
ADD files/vimrc /root/.vimrc
ENTRYPOINT ["/init.sh"]